### ISSUE TITLE
リンクをホバーしただけで画面遷移したことにしない修正

### ISSUE THREAD

**Issue by pakira-56A** [pakira-56A/aruaru-game#239]

**Comment by pakira-56A** [comment]
- **CSS**
  - [`app/assets/stylesheets/application.tailwind.css`](https://github.com/pakira-56A/aruaru-game/blob/main/app/assets/stylesheets/application.tailwind.css)
      画像のリンクにはホバーした際に、別の画像が表示されれる記載をしてます
     以下の記載を消しても、現象は起きました
      ```css
      ...
      /* メニュー */
      .menus-btn :hover{ content: url('header/menu/menus-hover.svg');}
      .menu-list1 a:hover #image-menu1 { content: url('header/menu/menu-1-hover.svg');}
      .menu-list2 a:hover #image-menu2 { content: url('header/menu/menu-2-hover.svg');}
      .menu-list3 a:hover #image-menu3 { content: url('header/menu/menu-3-hover.svg');}
      .menu-list4 a:hover #image-menu4 { content: url('header/menu/menu-4-hover.svg');}
      
      /* 投稿の詳細・ゲーム・編集・削除ボタン */
      .post-show a:hover #image-show{ content: url('post/post-show-hover.svg');}
      .post-game a:hover #image-game { content: url('post/post-game-hover.svg');}
      .post-edit a:hover #image-edit{ content: url('post/post-edit-hover.svg');}
      .post-delete a:hover #image-delete{ content: url('post/post-delete-hover.svg');}
      
      /* Xシェアボタン */
      .twitter a:hover #image-xshare { content: url('xshare-hover.svg');}
      ...
      ```
